version: '3.9'

services:
  project_front:
    container_name: project_front
    image: dylanerdini/project_front
    build: ./frontend
    ports:
      - 5173:5173
    environment:
      - API_ENDPOINT=http://localhost:8080/api
    depends_on: 
      - project_app

  project_app:
    container_name: project_app
    image: dylanerdini/project_app:1.0.0
    build: ./finalproject
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://project_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - project_db

  project_db:
    container_name: project_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}